zuul:
  routes:
    forex-service:
      path: /forex/**
      service-id: forex-service
      sensitive-headers: 
    db-service:
      path: /currency-converter/**
      service-id: currency-conversion-service
      sensitive-headers: 
#  ignored-headers: Authorization
#  ignore-security-headers: false
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    
server:
  port: 8084
  
spring:
  application:
    name: zuul-service